name: Workflow con Triggers

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Mensaje
        run: echo "Workflow ejecutado correctamente"

      - name: Fecha
        run: date

      - name: Usuario
        run: 'echo "Usuario: ${{ github.actor }}"'